### ISSUE TITLE
gpg packages need to be installed despite pgp feature not enabled

### ISSUE THREAD

**Issue by djmaze** [pimalaya/core#23]
Just tried to compile my app against the latest master (on NixOS). Had to gnupg and gpgme although I do not have `pgp-*` features enabled in my Cargo.toml.

**Comment by soywod** [comment]
- The [flake.nix](https://github.com/pimalaya/core/blob/119975060c78b7632d1760a823428bf6ca07bb03/flake.nix#L36-L37) from the current repository does not link Cargo features with Nix, this could definitely be a nice improvement.
- That said, the current version on nixpkgs [does the link](https://github.com/NixOS/nixpkgs/blob/991c0e8c9cd35636c5a7c91e4f62c0942b172fab/pkgs/by-name/hi/himalaya/package.nix#L46), could you share your Nix code?

I would advise not to use actual versions on repositories because they are not up-to-date (due to the beta). The `v1.0.0` is being tested on `master`, which I would recommand to use instead.

**Comment by djmaze** [comment]
I am building my own app which uses the email-lib crate (latest `master`) with a custom (non-flake) `shell.nix`. But I think it does matter. I just want to propose that it should be possible to use the email-lib crate without the gpg dependencies, as the `pgp-*` features are already optional in the codebase.

**Comment by soywod** [comment]
> I just want to propose that it should be possible to use the email-lib crate without the gpg dependencies, as the `pgp-*` features are already optional in the codebase

Yes I agree, I just have no idea how to do with nix flakes. Last time I searched, it was not possible to pass arguments to the nix build.

**Comment by soywod** [comment]
Duplicate https://github.com/pimalaya/core/issues/22.
